"""add rating

Revision ID: 98b5e129a089
Revises: d84b81b0faa0
Create Date: 2022-06-21 00:33:22.489098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b5e129a089'
down_revision = 'd84b81b0faa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rating_sum', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('rating_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating_num')
    op.drop_column('books', 'rating_sum')
    # ### end Alembic commands ###
