"""empty message

Revision ID: b42e604f68a4
Revises: 5bd32d89d9c3
Create Date: 2022-06-22 21:00:39.297545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42e604f68a4'
down_revision = '5bd32d89d9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_genres_genres_id_genres', 'books_genres', type_='foreignkey')
    op.drop_constraint('fk_books_genres_books_id_books', 'books_genres', type_='foreignkey')
    op.create_foreign_key(op.f('fk_books_genres_genres_id_genres'), 'books_genres', 'genres', ['genres_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_books_genres_books_id_books'), 'books_genres', 'books', ['books_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_covers_book_id_books', 'covers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_covers_book_id_books'), 'covers', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_reviews_book_id_books', 'reviews', type_='foreignkey')
    op.drop_constraint('fk_reviews_user_id_users', 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_reviews_book_id_books'), 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_role_id_roles'), 'users', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_role_id_roles'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(op.f('fk_reviews_book_id_books'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key('fk_reviews_user_id_users', 'reviews', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_reviews_book_id_books', 'reviews', 'books', ['book_id'], ['id'])
    op.drop_constraint(op.f('fk_covers_book_id_books'), 'covers', type_='foreignkey')
    op.create_foreign_key('fk_covers_book_id_books', 'covers', 'books', ['book_id'], ['id'])
    op.drop_constraint(op.f('fk_books_genres_books_id_books'), 'books_genres', type_='foreignkey')
    op.drop_constraint(op.f('fk_books_genres_genres_id_genres'), 'books_genres', type_='foreignkey')
    op.create_foreign_key('fk_books_genres_books_id_books', 'books_genres', 'books', ['books_id'], ['id'])
    op.create_foreign_key('fk_books_genres_genres_id_genres', 'books_genres', 'genres', ['genres_id'], ['id'])
    # ### end Alembic commands ###
